version: '3.8'

services:
  web:
    build:
      context: ./docker/backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  celery:
    build:
      context: ./docker/celery
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: