# Generated by Django 5.1.3 on 2024-11-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='highest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='frequency',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='target_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
