# Generated by Django 5.1.3 on 2024-11-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_challenge_highest_streak_alter_challenge_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchallenge',
            name='finish_date',
        ),
    ]
