# Generated by Django 5.1.3 on 2024-11-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userchallenge_finish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='highest_streak',
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='highest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
