# Generated by Django 5.1.3 on 2024-12-07 05:11

import core.models.challenge
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_challenge_highest_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='background_image',
            field=models.ImageField(blank=True, null=True, storage=core.models.challenge.MinioStorage(), upload_to=core.models.challenge.challenge_image_path),
        ),
        migrations.AddField(
            model_name='challenge',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.models.challenge.MinioStorage(), upload_to=core.models.challenge.challenge_image_path),
        ),
    ]
