# Generated by Django 5.1.3 on 2024-12-27 15:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
