# Generated by Django 5.1.3 on 2025-01-21 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_permission_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='members',
            field=models.ManyToManyField(related_name='challenges', through='core.UserChallenge', to=settings.AUTH_USER_MODEL),
        ),
    ]
