# Generated by Django 5.1.3 on 2025-01-24 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_challenge_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
